allen = User.create(email: "allen@bigfish.com", password: "Ab123456", name: "Allen")
harry = User.create(email: "harry@bigfish.com", password: "Ab123456", name: "Harry Potter", avatar_url: "https://ibin.co/4PR2pdJOyrb7.jpg")
ron = User.create(email: "ron@bigfish.com", password: "Ab123456", name: "Ron Weasley", avatar_url: "https://ibin.co/4PR39vYCcuYb.png")
hermione = User.create(email: "hermione@bigfish.com", password: "Ab123456", name: "Hermione Granger", avatar_url: "https://ibin.co/w800/4PR3V9rVBH1N.jpg")

question_allen_1 = Question.create(title: "Batman (creative franchise): How has Bruce Wayne acquired so many skills?", user: allen)
question_hermione_1 = Question.create(title: "How does one become a classy woman? What makes a woman classy?", user: hermione)
question_hermione_2 = Question.create(title: "What happens to the bullet if a gun is fired vertically upward from Earth's surface?", content: "What happens to the bullet if a gun is fired vertically upward from Earth's surface? Does it escape the Earth's gravitational field?", user: hermione)

answer_question_allen_1_1 = Answer.create(content: "The traumatic death of Bruce Wayne's parents as a child gave him a very strong sense of purpose from a young age. He then inherited a vast fortune that ensured that money would never be a concern in his life. The killer of Bruce's parents is caught and sent to prison, but years later is being released as he testified against his boss, a notorious crime lord of Gotham. Bruce, infuriated, grabs a gun and goes out to kill that man himself, but it's too late. The crime lord's assassin has already taken him out. Bruce then confronts the crime lord, who tells him that the greatest power is \"Fear!\". This leaves a powerful impact with the young billionaire with a thirst for a vengeance (that someone else drank right in front of him, which just makes him madder).\n\nLlike many a soul searching young American, Bruce decides he will learn about the seedy underbelly of the world by backpacking across Asia.", question: question_allen_1, user: harry)
answer_question_allen_1_2 = Answer.create(content: "Bruce's huge explosion kills the chief crime ninja and most of his students, though he managed to rescue the english speaker and the murderer from the blaze. The murderer, tears in his eyes, thanks Bruce and runs off.\n\nWith Bruce's backpacking trip ending in multi-man murder Bruce Wayne calls up his butler (whose been busy keeping the Wayne mansion from getting dusty), tells the butler he's learned lots of important life lessons and flies back to America to become the watchful protector of Gotham city. He then spends some of his trust fund bucks on really cool gadgets. Batman begins.", question: question_allen_1, user: ron)
answer_question_allen_1_3 = Answer.create(content: "Reinforcing the negative stereotype of the hooligan American backpacker, Bruce Wayne gets thrown in prison by Bhutanese authorities, where he gets into a lot of fights because nobody likes him (Bruce doesn't speak Dzongkha though, so they are polite enough to yell at him in English).", question: question_allen_1, user: hermione)

answer_question_hermione_2 = Answer.create(content: "No, it will not escape the Earth's gravitational field. The escape velocity at the Earth's surface is approximately 11.3 km/sec.  Gun muzzle velocities range from about 120 m/s to about 1,200 m/s depending on the gun. The highest muzzle velocity is about at least a factor of 10 too slow!  (At the low muzzle velocity end it would be a factor of 100 too slow!)  So there is no way to have a gun powerful enough to reach escape velocity for the bullet.\n\nIf you did manage to make a gun powerful enough to reach escape velocity, it still would not work. The problem is our atmosphere: the bullet would melt and disintegrate in the atmosphere in exactly the way that meteors burn up in the upper atmosphere.\n\nIt would be a better world if the bullets did all exceed escape velocity since the bullet coming back down to Earth can kill people. See and upvote Balaji Viswanathan's answer to this question.", question: question_hermione_2, user: allen)
